package org.ual.hmis.equipo3;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class S6RegistroFailsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private int browser;
  @Before
  public void setUp() {
	// Browser selector
	   browser=0; // 0: firefox, 1: chrome,...
	   boolean headless = false;

	   switch (browser) {
	   case 0:  // firefox
		   // Firefox
		   // Descargar geckodriver de https://github.com/mozilla/geckodriver/releases
		   // Descomprimir el archivo geckodriver.exe en la carpeta drivers
//		   System.setProperty("webdriver.gecko.driver",  "drivers/geckodriver.exe");
		   FirefoxOptions firefoxOptions = new FirefoxOptions();
		   FirefoxProfile firefoxProfile = new FirefoxProfile();
		   firefoxProfile.setPreference("intl.accept_languages", "es-ES");
		   firefoxOptions.setProfile(firefoxProfile);
		   if (headless) firefoxOptions.setHeadless(headless);
		   driver = new FirefoxDriver(firefoxOptions);

	   break;
	   case 1: // chrome
		   // Chrome
		   // Descargar Chromedriver de https://chromedriver.chromium.org/downloads
		   // Descomprimir el archivo chromedriver.exe en la carpeta drivers

//		   System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
		   ChromeOptions chromeOptions = new ChromeOptions();
		   chromeOptions.addArguments("--lang= es");
		   if (headless) chromeOptions.setHeadless(headless);
		   chromeOptions.addArguments("window-size=1920,1080");
		   driver = new ChromeDriver(chromeOptions);

		   break;

	   default:
		   	fail("Please select a browser");
		   	break;
	   }
	   js = (JavascriptExecutor) driver;
	   vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void s6RegistroFails() {
    // Test name: S6RegistroFails
    // Step # | name | target | value
	  vars.put("navigatorLanguage", js.executeScript("return navigator.language"));
    // 1 | open | https://hmis06.azurewebsites.net/ | 
    driver.get("https://hmis06.azurewebsites.net/");
    // 2 | setWindowSize | 945x1020 | 
    driver.manage().window().setSize(new Dimension(945, 1020));
    // 3 | click | linkText=Sign up | 
    driver.findElement(By.linkText("Sign up")).click();
    // 4 | waitForElementVisible | css=.ajax-button | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".ajax-button")));
    }
    // 5 | click | css=.ajax-button | 
    driver.findElement(By.cssSelector(".ajax-button")).click();
    // 6 | assertText | css=.form-group:nth-child(1) > .invalid-feedback | Please enter your full name.
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(1) > .invalid-feedback")).getText(), is("Please enter your full name."));
    // 7 | assertText | css=.form-group:nth-child(2) > .invalid-feedback | Please enter a valid email address.
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(2) > .invalid-feedback")).getText(), is("Please enter a valid email address."));
    // 8 | assertText | css=.form-group:nth-child(3) > .invalid-feedback | Please enter a password.
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(3) > .invalid-feedback")).getText(), is("Please enter a password."));
    // 9 | assertText | css=.form-group:nth-child(4) > .invalid-feedback | Your password and confirmation do not match.
    assertThat(driver.findElement(By.cssSelector(".form-group:nth-child(4) > .invalid-feedback")).getText(), is("Your password and confirmation do not match."));
    // 10 | type | id=full-name | ej1
    driver.findElement(By.id("full-name")).sendKeys("ej1");
    // 11 | type | id=email-address | ej1
    driver.findElement(By.id("email-address")).sendKeys("ej1");
    // 12 | type | id=password | ej1
    driver.findElement(By.id("password")).sendKeys("ej1");
    // 13 | type | id=confirm-password | ej1
    driver.findElement(By.id("confirm-password")).sendKeys("ej1");
    // 14 | click | css=.button-text | 
    driver.findElement(By.cssSelector(".button-text")).click();
    // 15 | executeScript | return document.getElementById("email-address").validationMessage | message
    vars.put("message", js.executeScript("return document.getElementById(\"email-address\").validationMessage"));
    // 16 | assert | message | Incluye un signo "@" en la dirección de correo electrónico. La dirección "ej1" no incluye el signo "@".
    if(browser==1)
    	assertEquals(vars.get("message").toString(), "Incluye un signo \"@\" en la dirección de correo electrónico. La dirección \"ej1\" no incluye el signo \"@\".");
    else {
    	  if ((Boolean) js.executeScript("return (arguments[0].includes(\'es\'))", vars.get("navigatorLanguage"))) 
    		  assertEquals(vars.get("message").toString(), "Introduzca una dirección de correo.");
    	  else
    		  assertEquals(vars.get("message").toString(), "Please enter an email address.");
    }
    	
    // 17 | type | id=email-address | ej1@ual
    driver.findElement(By.id("email-address")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
    driver.findElement(By.id("email-address")).sendKeys("ej1@ual");
    // 18 | click | css=.button-text | 
    driver.findElement(By.cssSelector(".button-text")).click();
    // 19 | assertText | css=.invalid-feedback | Please enter a valid email address.
    assertThat(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), is("Please enter a valid email address."));
    // 20 | type | id=email-address | ej1@ual.es
    driver.findElement(By.id("email-address")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
    driver.findElement(By.id("email-address")).sendKeys("ej1@ual.es");
    // 21 | click | css=.ajax-button | 
    driver.findElement(By.cssSelector(".ajax-button")).click();
    // 22 | assertNotChecked | id=terms-agreement | 
    assertFalse(driver.findElement(By.id("terms-agreement")).isSelected());
    // 23 | click | id=terms-agreement | 
    driver.findElement(By.id("terms-agreement")).click();
    // 24 | click | css=.ajax-button | 
    driver.findElement(By.cssSelector(".ajax-button")).click();
    // 25 | waitForElementVisible | css=.text-danger | 30000
    
    if (browser==1){
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".text-danger")));
    }
    else {
    	WebDriverWait wait = new WebDriverWait(driver, 30);
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[@id=\'signup\']/div/div/form/div[6]/p")));
    }
    // 26 | assertText | css=.text-danger | It looks like there's already an account with your email address. If you forgot your password, you can recover it here.
    if(browser==1)
    	assertThat(driver.findElement(By.cssSelector(".text-danger")).getText(), is("It looks like there's already an account with your email address. If you forgot your password, you can recover it here."));
    else
    	assertThat(driver.findElement(By.xpath("//div[@id=\'signup\']/div/div/form/div[6]/p")).getText(), is("It looks like there's already an account with your email address. If you forgot your password, you can recover it here."));
  }
}
